<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class SqlDataSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        // Table: acc_admins
        DB::table('acc_admins')->truncate();
        $rows_acc_admins = [
            [
                'id' => 1,
                'name' => 'Adriel Felix',
                'password' => '$2y$10$prw.1MGQWesBAdiTZOdUzeMSsbOFCv104qQG/7kxYFsZ6V2DYTFoy',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
        ];
        foreach (array_chunk($rows_acc_admins, 50) as $chunk) {
            DB::table('acc_admins')->insert($chunk);
        }

        // Table: banner
        DB::table('banner')->truncate();
        $rows_banner = [
            [
                'id' => 1,
                'gambar' => '1715574798.jpg',
                'nama' => 'Avengerr',
                'lokasi' => 'Search',
                'tglfilm' => '2024-05-13',
                'jamfilm' => '01:50',
                'status' => 'Publish',
                'remember_token' => null,
                'created_at' => '2024-05-12 21:33:18',
                'updated_at' => '2024-05-12 21:34:05',
            ],
            [
                'id' => 2,
                'gambar' => '1715574836.jpg',
                'nama' => 'Anime',
                'lokasi' => 'Search',
                'tglfilm' => '2024-05-13',
                'jamfilm' => '11:33',
                'status' => 'Publish',
                'remember_token' => null,
                'created_at' => '2024-05-12 21:33:56',
                'updated_at' => '2024-05-12 21:34:10',
            ],
            [
                'id' => 3,
                'gambar' => '1715644047.jpg',
                'nama' => 'Mario',
                'lokasi' => 'Search',
                'tglfilm' => '2024-05-14',
                'jamfilm' => '06:47',
                'status' => 'Publish',
                'remember_token' => null,
                'created_at' => '2024-05-13 16:47:27',
                'updated_at' => '2024-05-13 16:47:27',
            ],
            [
                'id' => 4,
                'gambar' => '1715644222.jpg',
                'nama' => 'Kimi no nawa',
                'lokasi' => 'Utama',
                'tglfilm' => '2024-05-14',
                'jamfilm' => '06:49',
                'status' => 'Publish',
                'remember_token' => null,
                'created_at' => '2024-05-13 16:50:22',
                'updated_at' => '2024-05-13 16:50:22',
            ],
            [
                'id' => 5,
                'gambar' => '1715644325.jpg',
                'nama' => 'The Roundup',
                'lokasi' => 'Utama',
                'tglfilm' => '2024-05-14',
                'jamfilm' => '06:51',
                'status' => 'Publish',
                'remember_token' => null,
                'created_at' => '2024-05-13 16:52:05',
                'updated_at' => '2024-05-13 16:52:05',
            ],
            [
                'id' => 7,
                'gambar' => '1715645173.jpg',
                'nama' => 'Sonic',
                'lokasi' => 'Utama',
                'tglfilm' => '2024-05-14',
                'jamfilm' => '07:05',
                'status' => 'Publish',
                'remember_token' => null,
                'created_at' => '2024-05-13 17:06:13',
                'updated_at' => '2024-05-13 17:06:13',
            ],
            [
                'id' => 8,
                'gambar' => '1717213801.jpg',
                'nama' => 'Haikkyuu',
                'lokasi' => 'Utama',
                'tglfilm' => '2024-06-01',
                'jamfilm' => '10:49',
                'status' => 'Publish',
                'remember_token' => null,
                'created_at' => '2024-05-31 20:50:01',
                'updated_at' => '2024-05-31 20:50:01',
            ],
            [
                'id' => 9,
                'gambar' => '1717213986.jpg',
                'nama' => 'Demon Slayer To the Hashira Training',
                'lokasi' => 'Search',
                'tglfilm' => '2024-06-01',
                'jamfilm' => '10:52',
                'status' => 'Publish',
                'remember_token' => null,
                'created_at' => '2024-05-31 20:53:06',
                'updated_at' => '2024-05-31 20:53:06',
            ],
            [
                'id' => 10,
                'gambar' => '1717214248.jpg',
                'nama' => 'Despicable Me 4',
                'lokasi' => 'Utama',
                'tglfilm' => '2024-06-01',
                'jamfilm' => '10:57',
                'status' => 'Publish',
                'remember_token' => null,
                'created_at' => '2024-05-31 20:57:28',
                'updated_at' => '2024-05-31 20:57:28',
            ],
            [
                'id' => 11,
                'gambar' => '1717214427.jpg',
                'nama' => 'Avengers: The Kang Dynasty',
                'lokasi' => 'Search',
                'tglfilm' => '2026-06-01',
                'jamfilm' => '11:00',
                'status' => 'Publish',
                'remember_token' => null,
                'created_at' => '2024-05-31 21:00:27',
                'updated_at' => '2024-05-31 21:00:27',
            ],
        ];
        foreach (array_chunk($rows_banner, 50) as $chunk) {
            DB::table('banner')->insert($chunk);
        }

        // Table: episodes
        DB::table('episodes')->truncate();
        $rows_episodes = [
            [
                'id' => 1,
                'episode' => '1',
                'season_id' => 1,
                'serial' => '12',
                'judul' => 'The Outsider',
                'thumb_eps' => '17156793381617788738.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'test',
                'created_at' => '2024-05-14 02:35:39',
                'updated_at' => '2024-05-14 02:35:39',
            ],
            [
                'id' => 2,
                'episode' => '2',
                'season_id' => 1,
                'serial' => '12',
                'judul' => 'Mysterious Guy',
                'thumb_eps' => '1717220666684220173.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Anna meminta Leo menjadi pacarnya demi melancarkan penyelidikan. Konflik mulai berdatangan khususnya dari anggota Griffin yang tidak menyukai Anna, dan Krystal, mantan kekasih Leo.',
                'created_at' => '2024-05-31 22:44:27',
                'updated_at' => '2024-05-31 22:44:27',
            ],
            [
                'id' => 3,
                'episode' => '3',
                'season_id' => 1,
                'serial' => '12',
                'judul' => 'Yellow Flag',
                'thumb_eps' => '1717220667278884187.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Penyelidikan Anna mengarah pada sosok Eros yang merupakan anggota Griffin. Bersamaan dengan itu, anak-anak Griffin mulai mencurigai kehadiran Anna yang diduga punya maksud tertentu.',
                'created_at' => '2024-05-31 22:44:27',
                'updated_at' => '2024-05-31 22:44:27',
            ],
            [
                'id' => 4,
                'episode' => '4',
                'season_id' => 1,
                'serial' => '12',
                'judul' => 'Lies & Betrayal',
                'thumb_eps' => '1717220667237002993.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Anna dituduh ada kaitannya dengan kematian Eros. Krystal berusaha keras untuk menjauhkan Anna dari Leo dan Griffin, tapi malah Krystal yang akhirnya dikeluarkan.',
                'created_at' => '2024-05-31 22:44:27',
                'updated_at' => '2024-05-31 22:44:27',
            ],
            [
                'id' => 5,
                'episode' => '5',
                'season_id' => 1,
                'serial' => '12',
                'judul' => 'Frenemy',
                'thumb_eps' => '1717220667183862954.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Perpecahan mulai terjadi di Griffin. Anna yang sudah pacaran dengan Leo mengalami banyak konflik, sementara itu, Dylan, wakil Griffin, dicurigai jadi orang yang membunuh Jones.',
                'created_at' => '2024-05-31 22:44:27',
                'updated_at' => '2024-05-31 22:44:27',
            ],
            [
                'id' => 6,
                'episode' => '6',
                'season_id' => 1,
                'serial' => '12',
                'judul' => 'Toxic',
                'thumb_eps' => '17172206671959851511.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Krystal mulai menyelidiki tentang Anna dari Thunder. Anna bersama Leo dan yang lain mengejar orang yang selama ini mereka cari.',
                'created_at' => '2024-05-31 22:44:27',
                'updated_at' => '2024-05-31 22:44:27',
            ],
            [
                'id' => 7,
                'episode' => '7',
                'season_id' => 1,
                'serial' => '12',
                'judul' => 'The Black Hero',
                'thumb_eps' => '17172206671189473136.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Leo dan Thunder terpaksa bersatu demi menyelesaikan misi Anna. Tapi Dylan yang mereka curigai selama ini, sekarang dalam keadaan koma.',
                'created_at' => '2024-05-31 22:44:27',
                'updated_at' => '2024-05-31 22:44:27',
            ],
            [
                'id' => 9,
                'episode' => '1',
                'season_id' => 2,
                'serial' => '18',
                'judul' => 'Tempat untuk Pulang',
                'thumb_eps' => '17172218671680194236.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Hutang menumpuk, rumah akan disita, Ical menghilang. Elzan dan Jamila sepakat mengadakan pertarungan gelap untuk mendatangkan banyak uang.',
                'created_at' => '2024-05-31 23:04:27',
                'updated_at' => '2024-05-31 23:04:27',
            ],
            [
                'id' => 10,
                'episode' => '2',
                'season_id' => 2,
                'serial' => '18',
                'judul' => 'Barat dan Timur',
                'thumb_eps' => '17172218671974160512.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Elzan bergabung dengan Rio dan Ara menjadi anak buah Tony. Ical melancarkan ambisinya menguasai pasar.',
                'created_at' => '2024-05-31 23:04:27',
                'updated_at' => '2024-05-31 23:04:27',
            ],
            [
                'id' => 11,
                'episode' => '3',
                'season_id' => 2,
                'serial' => '18',
                'judul' => 'Peperangan',
                'thumb_eps' => '17172218671256638008.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Perang antara dua geng preman di pasar membuat posisi Ical semakin penting sekaligus genting. Elzan bertemu kembali dengan musuh besarnya di penjara.',
                'created_at' => '2024-05-31 23:04:27',
                'updated_at' => '2024-05-31 23:04:27',
            ],
            [
                'id' => 12,
                'episode' => '4',
                'season_id' => 2,
                'serial' => '18',
                'judul' => 'Jeruji dan Kepalan Besi',
                'thumb_eps' => '1717221867765444310.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Kilas balik kehidupan Elzan dan Rio di penjara, dan awal pertentangan mereka dengan Romo. Ical tidak menyadari bahwa ada musuh dalam selimut.',
                'created_at' => '2024-05-31 23:04:27',
                'updated_at' => '2024-05-31 23:04:27',
            ],
            [
                'id' => 13,
                'episode' => '5',
                'season_id' => 2,
                'serial' => '18',
                'judul' => 'Rencana-Rencana',
                'thumb_eps' => '171722186791618309.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Elzan terseret dalam intrik preman pasar, dan menggunakannya untuk dekat kembali dengan Ical. Rio berjuang mempertahankan hidup anaknya.',
                'created_at' => '2024-05-31 23:04:27',
                'updated_at' => '2024-05-31 23:04:27',
            ],
            [
                'id' => 14,
                'episode' => '6',
                'season_id' => 2,
                'serial' => '18',
                'judul' => 'Doa dan Pendosa',
                'thumb_eps' => '1717221867708166897.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Elzan dan Rio mencurangi sistem penagihan utang, dan mengeruk keuntungan demi memenuhi kebutuhan keluarga mereka. Ical kembali datang ke rumah.',
                'created_at' => '2024-05-31 23:04:27',
                'updated_at' => '2024-05-31 23:04:27',
            ],
            [
                'id' => 15,
                'episode' => '7',
                'season_id' => 2,
                'serial' => '18',
                'judul' => 'Waktu Para Serigala',
                'thumb_eps' => '1717221867571485109.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Mereka dalam bahaya, sekaligus mengadu domba Elzan dan Ical.',
                'created_at' => '2024-05-31 23:04:27',
                'updated_at' => '2024-05-31 23:04:27',
            ],
            [
                'id' => 16,
                'episode' => '8',
                'season_id' => 2,
                'serial' => '18',
                'judul' => 'Pertaruhan',
                'thumb_eps' => '17172218671523933033.webp',
                'vid_eps' => 'https://www.youtube.com/watch?v=HZarmNqfL7s',
                'is_publish' => true,
                'desk_eps' => 'Elzan harus menghentikan Tony, dan berhadapan dengan Romo. Ara mendesak Ical untuk mengambil keputusan yang terbaik.',
                'created_at' => '2024-05-31 23:04:27',
                'updated_at' => '2024-05-31 23:04:27',
            ],
        ];
        foreach (array_chunk($rows_episodes, 50) as $chunk) {
            DB::table('episodes')->insert($chunk);
        }

        // Table: films
        DB::table('films')->truncate();
        $rows_films = [
            [
                'id' => 1,
                'judul' => 'Kisah Tanah Jawa Poncong Gundul',
                'thumbnail' => '1715588315.jpg',
                'deskripsi' => 'test',
                'tahun' => 2022,
                'usia' => '17+',
                'perusahaan' => 'MD Pictures',
                'sutradara' => 'Sidharta Tata',
                'video' => 'https://youtu.be/xDkeXcSso5Y?si=tSKCPs-fjRmqp_tp',
                'durasi' => '1j 55mnt',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-13 01:18:35',
                'updated_at' => '2024-05-13 01:18:35',
            ],
            [
                'id' => 2,
                'judul' => 'KKN',
                'thumbnail' => '1715636357.jpg',
                'deskripsi' => 'test',
                'tahun' => 2023,
                'usia' => '17+',
                'perusahaan' => 'MD Pictures',
                'sutradara' => 'Sidharta Tata',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 55mnt',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-13 14:39:17',
                'updated_at' => '2024-05-13 14:39:17',
            ],
            [
                'id' => 4,
                'judul' => 'Kuntilanak',
                'thumbnail' => '1715636440.jpg',
                'deskripsi' => 'test',
                'tahun' => 2023,
                'usia' => '17+',
                'perusahaan' => 'MD Pictures',
                'sutradara' => 'Sidharta Tata',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 55mnt',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-13 14:40:40',
                'updated_at' => '2024-05-13 14:40:40',
            ],
            [
                'id' => 5,
                'judul' => 'Mata Batin 2',
                'thumbnail' => '1715637850.jpg',
                'deskripsi' => 'test',
                'tahun' => 2023,
                'usia' => '17+',
                'perusahaan' => 'MD Pictures',
                'sutradara' => 'Sidharta Tata',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 55mnt',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-13 15:04:10',
                'updated_at' => '2024-05-13 15:04:10',
            ],
            [
                'id' => 6,
                'judul' => 'Megan',
                'thumbnail' => '1715637901.jpg',
                'deskripsi' => 'test',
                'tahun' => 2023,
                'usia' => '17+',
                'perusahaan' => 'MD Pictures',
                'sutradara' => 'Sidharta Tata',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 55mnt',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-13 15:05:01',
                'updated_at' => '2024-05-13 15:05:01',
            ],
            [
                'id' => 7,
                'judul' => 'IT',
                'thumbnail' => '1715638094.jpg',
                'deskripsi' => 'test',
                'tahun' => 2022,
                'usia' => '17+',
                'perusahaan' => 'MD Pictures',
                'sutradara' => 'Sidharta Tata',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 55mnt',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-13 15:08:14',
                'updated_at' => '2024-05-13 15:08:14',
            ],
            [
                'id' => 8,
                'judul' => 'Dead Silence',
                'thumbnail' => '1715638190.jpg',
                'deskripsi' => 'test',
                'tahun' => 2022,
                'usia' => '17+',
                'perusahaan' => 'MD Pictures',
                'sutradara' => 'Sidharta Tata',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 55mnt',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-13 15:09:50',
                'updated_at' => '2024-05-13 15:09:50',
            ],
            [
                'id' => 9,
                'judul' => 'The Doll 3',
                'thumbnail' => '1715638858.jpg',
                'deskripsi' => 'test',
                'tahun' => 2023,
                'usia' => '17+',
                'perusahaan' => 'MD Pictures',
                'sutradara' => 'Sidharta Tata',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 55mnt',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-13 15:20:58',
                'updated_at' => '2024-05-13 15:20:58',
            ],
            [
                'id' => 10,
                'judul' => 'Saw',
                'thumbnail' => '1715638934.jpg',
                'deskripsi' => 'test',
                'tahun' => 2023,
                'usia' => '17+',
                'perusahaan' => 'MD Pictures',
                'sutradara' => 'Sidharta Tata',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 55mnt',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-13 15:22:14',
                'updated_at' => '2024-05-13 15:22:14',
            ],
            [
                'id' => 11,
                'judul' => 'The Conjuring',
                'thumbnail' => '1715639139.jpg',
                'deskripsi' => 'test',
                'tahun' => 2022,
                'usia' => '17+',
                'perusahaan' => 'MD Pictures',
                'sutradara' => 'Sidharta Tata',
                'video' => 'https://youtu.be/g4Hbz2jLxvQ?si=XnvNy3hACSf2-jxp',
                'durasi' => '1j 55mnt',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-13 15:25:39',
                'updated_at' => '2024-05-13 15:25:39',
            ],
            [
                'id' => 12,
                'judul' => 'Switchover',
                'thumbnail' => '1715676930.jpg',
                'deskripsi' => 'Kembalinya Anna ke Jakarta membawa kebahagiaan bagi Jones, ayahnya. Anna merasa tak nyaman setelah kematian Jones berkaitan dengan geng motor Griffin.',
                'tahun' => 2023,
                'usia' => '13+',
                'perusahaan' => 'Screenplay Films',
                'sutradara' => 'Angling Sagaran',
                'video' => null,
                'durasi' => '1',
                'view' => null,
                'kategori_id' => null,
                'tipe' => 'Serial',
                'is_publish' => true,
                'created_at' => '2024-05-14 01:55:30',
                'updated_at' => '2024-05-14 01:55:30',
            ],
            [
                'id' => 13,
                'judul' => 'Kalian Pantas Mati',
                'thumbnail' => '1717160261.jpg',
                'deskripsi' => 'Seorang pemuda yang memiliki kemampuan untuk berkomunikasi dengan orang yang sudah meninggal. Dia harus menggunakan kemampuannya untuk menghentikan roh jahat yang dipenuhi dendam terhadap teman sekolahnya. Sementara itu dia bertekad untuk membantu sesosok hantu cantik untuk mengembalikan ingatannya.',
                'tahun' => 2022,
                'usia' => '17+',
                'perusahaan' => 'Paragon Pictures',
                'sutradara' => 'Ginanti Rona',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 46m',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-31 05:57:41',
                'updated_at' => '2024-05-31 06:04:41',
            ],
            [
                'id' => 14,
                'judul' => 'Aku Tahu Kapan Kamu Mati',
                'thumbnail' => '1717160925.jpg',
                'deskripsi' => 'Setelah mengalami mati suri, Siena mendapatkan kemampuan untuk melihat kapan seseorang akan meninggal. Kemampuan tersebut ditandai dengan adanya sesosok hantu yang mengikuti orang yang akan meninggal. Korban pertama adalah siswi SMA yang bunuh diri, disusul oleh Pak Somad, tetangga Siena yang meninggal karena sakitnya kambuh. Korban ketiga adalah Brama, kakak kelas Siena, yang mulai mendekatinya pasca dia mengalami mati suri. Siena mencoba untuk meyakinkan tiga sahabatnya, Flo, Neni, dan Vina, akan kemampuannya. Mereka awalnya tidak percaya, sampai Brama tewas ditabrak truk tepat di depan mata mereka.',
                'tahun' => 2023,
                'usia' => '17+',
                'perusahaan' => 'Unlimited Production',
                'sutradara' => 'Oswin Bonifanz',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 34m',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-31 06:08:45',
                'updated_at' => '2024-05-31 06:08:45',
            ],
            [
                'id' => 15,
                'judul' => 'Waktu Maghrib',
                'thumbnail' => '1717161117.jpg',
                'deskripsi' => 'mengisahkan kisah seram yang berawal dari desa terpencil bernama Desa Jatijajar, Jawa Tengah, di mana tiga anak bernama Adi, Saman, dan Ayu tinggal. Mereka sering membantu keluarga mereka di ladang, yang mengakibatkan keterlambatan mereka ke sekolah.',
                'tahun' => 2023,
                'usia' => '17+',
                'perusahaan' => 'Rapi Films',
                'sutradara' => 'Sidharta Tata',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 44m',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-31 06:11:57',
                'updated_at' => '2024-05-31 06:11:57',
            ],
            [
                'id' => 16,
                'judul' => 'Sabrina',
                'thumbnail' => '1717161375.jpg',
                'deskripsi' => 'MAIRA hidup bahagia di pernikahan barunya bersama AIDEN, pembuat boneka Sabrina sekaligus pemilik sebuah perusahaan mainan. Tapi kebahagiaan mereka belum sempurna karena VANYA, anak angkat sekaligus keponakan Aiden yang yang piatu belum bisa menerima kehadiran Maira sebagai ibunya karena Vanya masih belum bisa merelakan kepergian ANDINI, bundanya yang sudah meninggal. Suatu hari, Vanya melakukan permainan ‘Pensil Charlie’ untuk memanggil bundanya dan kejanggalan-kejanggalan pun mulai terjadi. Maira dan Aiden Adak percaya, hingga akhirnya Maira mengalami serentetan kejadian menakutkan dan mereka melihat sendiri sosok Andini. Maira pun memanggil BU LARAS, seorang paranormal yang dulu pernah membantunya. Tapi Andini ternyata bukanlah Andini, melainkan iblis keji bernama BAGHIAH yang menetap di boneka Sabrina dan menginginkan tubuh manusia...',
                'tahun' => 2018,
                'usia' => '17+',
                'perusahaan' => 'Mirage Enterprises Sandollar Productions',
                'sutradara' => 'Rocky Soraya',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 52m',
                'view' => null,
                'kategori_id' => null,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-31 06:16:15',
                'updated_at' => '2024-05-31 06:16:15',
            ],
            [
                'id' => 17,
                'judul' => 'Mereka Yang Tak Terlihat',
                'thumbnail' => '1717161615.jpg',
                'deskripsi' => 'Saras (Estelle Linden), seorang anak indigo yang bisa melihat makhluk-makhluk tak kasatmata sejak ia kecil. Ia merupakan putri dari Lidya (Sophia Latjuba), seorang single parent yang memiliki usaha kue kering untuk menyambung hidup. Ia memiliki adik bernama Laras. Lidya sendiri menganggap kelebihan Saras tidak masuk akal, sehingga membuat hubungan ibu dan anak itu menjadi berjarak. Lidya semakin lama semakin tidak mengerti dengan tingkah Saras.

Di usia 17 tahun, Saras dua kali kesurupan dan hal ini membuat Lidya sangat khawatir dan meminta kakaknya yang bernama Tante Rima (Roweina Umboh), seorang psikolog, untuk menangani Saras. Namun, Tante Rima bersikeras ke Lidya bahwa hanya Lidya lah yang harus menangani Saras sebagai ibu kandungnya. Sampai suatu hari Saras didatangi oleh arwah bernama Dinda (Frislly Herlind), siswi SMA yang meninggal karena dibully di sekolah oleh Citra (Aliyah Faizah). Arwah Dinda meminta Saras untuk menemui ibunya yang bernama Dayu (Dayu Wijanto). Dinda ingin agar Dayu ikhlas merelakan kepergiannya dan memaafkan Citra yang selama ini dianggap sebagai penyebab kematiannya. Hubungan Saras dengan Lidya semakin kritis ketika keduanya mengutarakan kekecewaan terhadap sikap masing-masing dan saling menyalahkan, sampai sebuah peristiwa besar terjadi dalam kehidupan keluarga mereka.',
                'tahun' => 2022,
                'usia' => '17+',
                'perusahaan' => 'Skylar Pictures',
                'sutradara' => 'Billy Christian',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'durasi' => '1j 34m',
                'view' => null,
                'kategori_id' => 1,
                'tipe' => 'Film',
                'is_publish' => true,
                'created_at' => '2024-05-31 06:20:15',
                'updated_at' => '2024-05-31 06:20:15',
            ],
            [
                'id' => 18,
                'judul' => 'Pertaruhan The Series',
                'thumbnail' => '1717220998.jpg',
                'deskripsi' => 'Walau berusaha keluar dari lingkaran setan, Elzan & Ical terseret ke skema kriminal yang dirancang Irfan. Bisakah mereka memenangkan pertaruhan ini?',
                'tahun' => 2023,
                'usia' => '17+',
                'perusahaan' => 'IFI Sinema',
                'sutradara' => 'Krishto D. Alam',
                'video' => null,
                'durasi' => '2 Season',
                'view' => null,
                'kategori_id' => null,
                'tipe' => 'Serial',
                'is_publish' => true,
                'created_at' => '2024-05-31 22:49:58',
                'updated_at' => '2024-05-31 22:49:58',
            ],
        ];
        foreach (array_chunk($rows_films, 50) as $chunk) {
            DB::table('films')->insert($chunk);
        }

        // Table: kategoris
        DB::table('kategoris')->truncate();
        $rows_kategoris = [
            [
                'id' => 1,
                'kategori' => 'Horror',
                'is_publish' => true,
                'created_at' => '2024-05-13 01:09:30',
                'updated_at' => '2024-05-13 01:15:32',
            ],
            [
                'id' => 4,
                'kategori' => 'Film Korea',
                'is_publish' => true,
                'created_at' => '2024-05-13 01:11:21',
                'updated_at' => '2024-05-13 01:11:21',
            ],
            [
                'id' => 5,
                'kategori' => 'Super Hero',
                'is_publish' => true,
                'created_at' => '2024-05-13 01:11:33',
                'updated_at' => '2024-05-13 01:11:33',
            ],
            [
                'id' => 6,
                'kategori' => 'Animasi Anak Anak',
                'is_publish' => true,
                'created_at' => '2024-05-13 15:27:10',
                'updated_at' => '2024-05-13 15:27:10',
            ],
            [
                'id' => 7,
                'kategori' => 'Anime Jepang',
                'is_publish' => true,
                'created_at' => '2024-05-13 15:27:29',
                'updated_at' => '2024-05-13 15:27:29',
            ],
            [
                'id' => 8,
                'kategori' => 'Film Indonesia',
                'is_publish' => true,
                'created_at' => '2024-05-13 15:27:59',
                'updated_at' => '2024-05-13 15:27:59',
            ],
        ];
        foreach (array_chunk($rows_kategoris, 50) as $chunk) {
            DB::table('kategoris')->insert($chunk);
        }

        // Table: laporans
        DB::table('laporans')->truncate();
        $rows_laporans = [
            [
                'id' => 1,
                'name' => 'flx',
                'laporan' => 'terjadi kesalahan saat ingin log out, tolong segera diperbaiki!',
                'lokasi' => 'Profil',
                'created_at' => '2024-05-31 21:19:21',
                'updated_at' => '2024-05-31 21:19:21',
            ],
            [
                'id' => 2,
                'name' => 'flx',
                'laporan' => 'tidak dapat mengubah foto profil dan saat mengubah password password lama salah terus tetap saya sudah menginputkan dengan benar.',
                'lokasi' => 'Profil',
                'created_at' => '2024-05-31 23:22:14',
                'updated_at' => '2024-05-31 23:22:14',
            ],
            [
                'id' => 3,
                'name' => 'flx',
                'laporan' => 'Halaman favorit dan daftar tonton nanti tidak bisa di buka, tolong segera perbaiki saya ingin ingin melihat daftar favorit dan daftar tontonan saya.',
                'lokasi' => 'Profil',
                'created_at' => '2024-05-31 23:24:20',
                'updated_at' => '2024-05-31 23:24:20',
            ],
            [
                'id' => 4,
                'name' => 'felix',
                'laporan' => 'Saya kesulitan menemukan film atau acara serial yang saya sukai di MUVIKU. Sistem rekomendasinya tidak sesuai dengan preferensi saya',
                'lokasi' => 'Profil',
                'created_at' => '2024-06-10 10:04:27',
                'updated_at' => '2024-06-10 10:04:27',
            ],
            [
                'id' => 5,
                'name' => 'felix',
                'laporan' => 'Fitur pencarian MUVIKU terlalu terbatas. Saya seringkali harus menghabiskan waktu lama untuk menemukan sesuatu yang ingin saya tonton.',
                'lokasi' => 'Profil',
                'created_at' => '2024-06-10 10:04:43',
                'updated_at' => '2024-06-10 10:04:43',
            ],
            [
                'id' => 6,
                'name' => 'felix',
                'laporan' => 'Saya tidak senang dengan kecepatan buffering yang lambat saat menonton konten di MUVIKU, meskipun saya memiliki koneksi internet yang cukup cepat',
                'lokasi' => 'Profil',
                'created_at' => '2024-06-10 10:05:03',
                'updated_at' => '2024-06-10 10:05:03',
            ],
            [
                'id' => 7,
                'name' => 'felix',
                'laporan' => 'Tidak adanya opsi untuk menyesuaikan subtitle atau audio dalam beberapa bahasa membuat pengalaman menonton saya kurang memuaskan.',
                'lokasi' => 'Profil',
                'created_at' => '2024-06-10 10:05:18',
                'updated_at' => '2024-06-10 10:05:18',
            ],
            [
                'id' => 8,
                'name' => 'felix',
                'laporan' => 'Saya sering mengalami gangguan atau pemutusan sinyal saat menonton konten streaming di MUVIKU, yang mengganggu pengalaman menonton saya.',
                'lokasi' => 'Profil',
                'created_at' => '2024-06-10 10:05:48',
                'updated_at' => '2024-06-10 10:05:48',
            ],
        ];
        foreach (array_chunk($rows_laporans, 50) as $chunk) {
            DB::table('laporans')->insert($chunk);
        }

        // Table: podcast
        DB::table('podcast')->truncate();
        $rows_podcast = [
            [
                'id' => 2,
                'judul' => 'DZAWIN NUR BONGKAR RITUAL ILMU PEMANGGIL KUNTILANAK DILANGIT KELABU BARENG PRAZ TEGUH!!',
                'channel' => 'HAS Creative',
                'host' => 'Praz Teguh',
                'deskripsi' => 'test',
                'view' => null,
                'thumbnail' => '1715640738.jpg',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'status' => 'Publish',
                'created_at' => '2024-05-13 15:52:18',
                'updated_at' => '2024-05-13 16:01:38',
            ],
            [
                'id' => 3,
                'judul' => 'Ganjar Marah Gara Gara  Video Loe!! Gue Telp Cak Imin!?',
                'channel' => 'Deddy Corbuzier',
                'host' => 'Deddy Corbuzier',
                'deskripsi' => 'test',
                'view' => null,
                'thumbnail' => '1715641030.jpg',
                'video' => 'https://youtu.be/dndhSSujEFQ?si=AyCXs1Hx9POyw9ys',
                'status' => 'Publish',
                'created_at' => '2024-05-13 15:57:10',
                'updated_at' => '2024-05-13 15:57:10',
            ],
            [
                'id' => 4,
                'judul' => 'BORIS BOKIR MALAH DIPUTUSIN CEWEK HABIS BAGI RAPOR',
                'channel' => 'HAS Creative',
                'host' => 'Praz Teguh',
                'deskripsi' => 'test',
                'view' => null,
                'thumbnail' => '1715641419.jpg',
                'video' => 'https://youtu.be/faJb9aRWGR0?si=dGkgOnSGjD2IDHeX',
                'status' => 'Publish',
                'created_at' => '2024-05-13 16:03:39',
                'updated_at' => '2024-05-13 16:03:39',
            ],
            [
                'id' => 5,
                'judul' => 'YAH BANGKRUT & JADI TULANG PUNGGUNG, PESULAP MERAH GAK SEMPET WUJUDIN CITA-CITA JADI SPIDERMAN',
                'channel' => 'HAS Creative',
                'host' => 'Praz Teguh',
                'deskripsi' => 'test',
                'view' => null,
                'thumbnail' => '1715642019.jpg',
                'video' => 'https://youtu.be/UioVRDFab3c?si=re2IAlSyowbDitf1',
                'status' => 'Publish',
                'created_at' => '2024-05-13 16:13:39',
                'updated_at' => '2024-05-13 16:13:39',
            ],
            [
                'id' => 6,
                'judul' => 'DODIT BIKIN NOVEL TENTANG MAKAM PONAKAN-NYA YANG DI BONGKAR DAN DIPAKE RITUAL PENJUAL BUNGA!',
                'channel' => 'HAS Creative',
                'host' => 'Praz Teguh',
                'deskripsi' => 'test',
                'view' => null,
                'thumbnail' => '1715642135.jpg',
                'video' => 'https://youtu.be/xnq5FjrE-QE?si=y4x_7jFUKbQhb5yi',
                'status' => 'Publish',
                'created_at' => '2024-05-13 16:15:35',
                'updated_at' => '2024-05-13 16:15:35',
            ],
            [
                'id' => 7,
                'judul' => 'SUDAH MENIKAH, MEGI IRAWAN PANIK DITANYA CEWE BERAMBUT PIRANG YANG DULU DIBAWA KE PWK',
                'channel' => 'HAS Creative',
                'host' => 'Praz Teguh',
                'deskripsi' => 'test',
                'view' => null,
                'thumbnail' => '1715642607.jpg',
                'video' => 'https://youtu.be/Q9u31hWsKOo?si=7cUvclW2Erom-NEZ',
                'status' => 'Publish',
                'created_at' => '2024-05-13 16:23:27',
                'updated_at' => '2024-05-13 16:23:27',
            ],
            [
                'id' => 13,
                'judul' => 'MISI HABIB JAFAR INGIN FOTO TOLERANSI BERAGAMA TIDAK LAGI VIRAL',
                'channel' => 'HAS Creative',
                'host' => 'Praz Teguh',
                'deskripsi' => 'test',
                'view' => null,
                'thumbnail' => '1715642762.jpg',
                'video' => 'https://youtu.be/SQBW_0hRNNg?si=PB0fcUZzLdISN2ik',
                'status' => 'Publish',
                'created_at' => '2024-05-13 16:26:02',
                'updated_at' => '2024-05-13 16:26:02',
            ],
            [
                'id' => 14,
                'judul' => 'HAPE ILANG PAS LAGI NGONTEN, DAVI SIUMBING DIBELIIN HAPE BARU SAMA NOPEK, TAPI DISURUH GANTI!',
                'channel' => 'HAS Creative',
                'host' => 'Praz Teguh',
                'deskripsi' => 'test',
                'view' => null,
                'thumbnail' => '1715643011.jpg',
                'video' => 'https://youtu.be/J_WuWM454cE?si=h-b4RV7bIHiW9tKr',
                'status' => 'Publish',
                'created_at' => '2024-05-13 16:30:11',
                'updated_at' => '2024-05-13 16:30:11',
            ],
            [
                'id' => 15,
                'judul' => 'KUKUH ADI INTROVERT, LIAT UFO DAN BISA NGERAGASUKMA, GARA-GARA SERING MAIN SAMA MAINAN!',
                'channel' => 'HAS Creative',
                'host' => 'Praz Teguh',
                'deskripsi' => 'test',
                'view' => null,
                'thumbnail' => '1715643220.jpg',
                'video' => 'https://youtu.be/TrSeG1FmT9k?si=7vSO7byvtJDjc_Xr',
                'status' => 'Publish',
                'created_at' => '2024-05-13 16:33:40',
                'updated_at' => '2024-05-13 16:33:40',
            ],
        ];
        foreach (array_chunk($rows_podcast, 50) as $chunk) {
            DB::table('podcast')->insert($chunk);
        }

        // Table: rekomendasis
        DB::table('rekomendasis')->truncate();
        $rows_rekomendasis = [
            [
                'id' => 2,
                'gambar' => '1715680708.jpg',
                'judul' => 'Demon Slayer',
                'deskripsi' => 'Pemburu Iblis',
                'tgl' => '2024-05-14',
                'jam' => '16:58',
                'status' => 'Publish',
                'created_at' => '2024-05-14 02:58:28',
                'updated_at' => '2024-05-14 02:58:28',
            ],
            [
                'id' => 3,
                'gambar' => '1715681225.jpg',
                'judul' => 'Ratatouille',
                'deskripsi' => 'Koki Tikus',
                'tgl' => '2024-05-14',
                'jam' => '17:00',
                'status' => 'Publish',
                'created_at' => '2024-05-14 03:07:05',
                'updated_at' => '2024-05-31 21:07:39',
            ],
            [
                'id' => 4,
                'gambar' => '1717165737.jpg',
                'judul' => 'KKN',
                'deskripsi' => 'Kisah Desa Penari',
                'tgl' => '2024-05-31',
                'jam' => '21:28',
                'status' => 'Publish',
                'created_at' => '2024-05-31 07:28:57',
                'updated_at' => '2024-05-31 07:28:57',
            ],
            [
                'id' => 5,
                'gambar' => '1717165815.webp',
                'judul' => 'Mr. Bean',
                'deskripsi' => 'Kelakuan Kocak',
                'tgl' => '2024-05-31',
                'jam' => '21:30',
                'status' => 'Publish',
                'created_at' => '2024-05-31 07:30:15',
                'updated_at' => '2024-05-31 07:30:15',
            ],
            [
                'id' => 7,
                'gambar' => '1717214810.jpg',
                'judul' => 'A Driver Taxi',
                'deskripsi' => 'Sopir Taxi Handal',
                'tgl' => '2024-06-01',
                'jam' => '11:06',
                'status' => 'Publish',
                'created_at' => '2024-05-31 21:06:50',
                'updated_at' => '2024-05-31 21:06:50',
            ],
        ];
        foreach (array_chunk($rows_rekomendasis, 50) as $chunk) {
            DB::table('rekomendasis')->insert($chunk);
        }

        // Table: seasons
        DB::table('seasons')->truncate();
        $rows_seasons = [
            [
                'id' => 1,
                'film_id' => 12,
                'season' => 1,
                'is_publish' => true,
                'created_at' => '2024-05-14 01:56:08',
                'updated_at' => '2024-05-14 01:56:08',
            ],
            [
                'id' => 2,
                'film_id' => 18,
                'season' => 1,
                'is_publish' => true,
                'created_at' => '2024-05-31 22:50:58',
                'updated_at' => '2024-05-31 22:50:58',
            ],
        ];
        foreach (array_chunk($rows_seasons, 50) as $chunk) {
            DB::table('seasons')->insert($chunk);
        }

        // Table: users
        DB::table('users')->truncate();
        $rows_users = [
            [
                'id' => 3,
                'name' => 'brahmana',
                'email' => 'brahmana@gmail.com',
                'nohp' => '088889988',
                'email_verified_at' => null,
                'password' => '$2y$12$hoCYMh798HdRCMltTkT3s.n6rWoU4qTl81c/paZtX3ZafSUoa6spm',
                'status' => 'Pengguna Lama',
                'gambar' => null,
                'remember_token' => null,
                'created_at' => '2024-05-31 23:26:10',
                'updated_at' => '2024-06-07 11:01:27',
                'google_id' => null,
            ],
            [
                'id' => 4,
                'name' => 'felix',
                'email' => 'felix@gmail.com',
                'nohp' => '089765623423',
                'email_verified_at' => null,
                'password' => '$2y$12$04cM3reFzYBXsHidMvCiX.myIq70RPQ3RradlNcfeAitj0rIoqeu2',
                'status' => null,
                'gambar' => null,
                'remember_token' => null,
                'created_at' => '2024-06-07 08:43:19',
                'updated_at' => '2024-06-07 08:43:19',
                'google_id' => null,
            ],
            [
                'id' => 5,
                'name' => 'ravanelo',
                'email' => 'rava@gmail.com',
                'nohp' => '088888888',
                'email_verified_at' => null,
                'password' => '$2y$12$b/.sXbAAy7nGJwChQJhE1OSZ2yJJiD5bDzurGoQF29IV5PhqVtNte',
                'status' => null,
                'gambar' => null,
                'remember_token' => null,
                'created_at' => '2024-06-09 04:46:13',
                'updated_at' => '2024-06-09 04:46:13',
                'google_id' => null,
            ],
            [
                'id' => 6,
                'name' => 'adrian',
                'email' => 'adrian@gmail.com',
                'nohp' => '08234242153',
                'email_verified_at' => null,
                'password' => '$2y$12$Yxr2PaclUiYqbBm8nQgZkO3Ul5d9zsDQ1N003TKg/3H0JSLWfD5Eu',
                'status' => null,
                'gambar' => null,
                'remember_token' => null,
                'created_at' => '2024-06-09 04:46:55',
                'updated_at' => '2024-06-09 04:46:55',
                'google_id' => null,
            ],
            [
                'id' => 7,
                'name' => 'Rangga',
                'email' => 'rangga@gmail.com',
                'nohp' => '0863545623',
                'email_verified_at' => null,
                'password' => '$2y$12$zFD7eCFtoSa/f2cG1Y1Xw.a5PLKLoQOMqUUQKKf/sivpOtAZ.5Doy',
                'status' => null,
                'gambar' => null,
                'remember_token' => null,
                'created_at' => '2024-06-09 04:47:32',
                'updated_at' => '2024-06-09 04:47:32',
                'google_id' => null,
            ],
            [
                'id' => 8,
                'name' => 'Ewing',
                'email' => 'ewing@gmail.com',
                'nohp' => '0862356143',
                'email_verified_at' => null,
                'password' => '$2y$12$DQYZXpV3kInij3sTLw9JZeNPNisyuXpjUpZ6E9JpXuYmeNkrB1WMS',
                'status' => null,
                'gambar' => '1717933882.jpg',
                'remember_token' => null,
                'created_at' => '2024-06-09 04:48:11',
                'updated_at' => '2024-06-09 04:51:22',
                'google_id' => null,
            ],
            [
                'id' => 9,
                'name' => 'Fahmi',
                'email' => 'fahmi@gmail.com',
                'nohp' => '0866513476',
                'email_verified_at' => null,
                'password' => '$2y$12$tIBdXuLu2Fg6wBPnts8Bl.tWfoFU3ojjreLI5a1wcghL90up9nAbq',
                'status' => null,
                'gambar' => null,
                'remember_token' => null,
                'created_at' => '2024-06-09 04:48:38',
                'updated_at' => '2024-06-09 04:48:38',
                'google_id' => null,
            ],
        ];
        foreach (array_chunk($rows_users, 50) as $chunk) {
            DB::table('users')->insert($chunk);
        }

        // Reset sequence IDs for PostgreSQL
        if (DB::getDriverName() === 'pgsql') {
            $tables = ['acc_admins', 'banner', 'episodes', 'films', 'kategoris', 'laporans', 'podcast', 'rekomendasis', 'seasons', 'users'];
            foreach ($tables as $tbl) {
                DB::statement("SELECT setval(pg_get_serial_sequence('{$tbl}', 'id'), coalesce(max(id),0) + 1, false) FROM {$tbl};");
            }
        }

        Schema::enableForeignKeyConstraints();
    }
}
